server:
  port: 8084

spring:
  rabbitmq:
    host: ${env.RABBIT_HOST}
    port: 5672 #Paliativo até encontrar solução para converter em Integer
    username: ${env.RABBIT_USERNAME}
    password: ${env.RABBIT_PASSWORD}